name: "resnet50_config_30"
platform: "tensorrt_plan"
max_batch_size: 64

input {
  name: "input"
  data_type: TYPE_FP32
  dims: 3
  dims: 224
  dims: 224
}

output {
  name: "output"
  data_type: TYPE_FP32
  dims: 1000
  label_filename: "labels.txt"
}

instance_group {
  count: 4
  kind: KIND_GPU
}

default_model_filename: "resnet50.plan"

dynamic_batching {
}
